name: ortemhealth_patient_app
description: Patient-facing OrtemHealth app
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
