name: ortemhealth_patient_app
description: Patient-facing OrtemHealth app
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
 flutter:
    sdk: flutter
  lottie: ^2.5.0
  http: ^1.2.0
  provider: ^6.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/onboard_animation.json
